# Generated by Django 5.1.6 on 2025-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ticket_total_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Happening', 'Happening')], default='Upcoming', max_length=100),
        ),
    ]
